# Generated by Django 4.0 on 2023-10-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.customuser')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('cet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shs_track', models.CharField(blank=True, max_length=255, null=True)),
                ('shs_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cet',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shs_gpa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shs_track',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
